import React from "react";

import { FaUpload, FaMagnifyingGlass, FaDatabase } from "react-icons/fa6";
import { BsStars } from "react-icons/bs";

import { useDropzone } from "react-dropzone";

const HomePage = () => {
  const onDrop = React.useCallback((acceptedFiles) => {
    console.log(acceptedFiles);
  }, []);
  const {
    acceptedFiles,
    fileRejections,
    getRootProps,
    getInputProps,
    isDragActive,
  } = useDropzone({
    onDrop,
    maxFiles: 1,
    accept: {
      "text/csv": [".csv"],
      "text/tab-separated-values": [".tsv"],
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [
        ".xlsx",
      ],
      "application/vnd.ms-excel": [".xls"],
    },
  });

  return (
    <div className="mx-2 md:mx-8 my-8 px-4 py-8 bg-section-base rounded-lg flex flex-col justify-center content-center text-center shadow-lg">
      <h1 className="md:w-3/5 text-5xl font-bold self-center text-pretty">
        Intelligent AI Powered Tool for{" "}
        <span className="bg-gradient-to-br from-primary to-primary/30 text-transparent bg-clip-text">
          Data Analysis{" "}
        </span>
        and{" "}
        <span className="bg-gradient-to-br from-primary to-primary/30 text-transparent bg-clip-text">
          Visualization
        </span>
      </h1>
      <p className="text-lg self-center py-4 text-black/40">
        Talk to your data and get expert-level insights and graphs in seconds.
      </p>

      <div className="flex flex-col lg:flex-row justify-center gap-4 text-left mt-16">
        <div className="flex flex-col justify-between p-4 rounded-b-lg lg:w-3/12 shadow-lg">
          <div>
            <h2 className="text-xl">
              <b className="flex gap-2">
                <FaUpload className="self-center" />
                Upload
              </b>
            </h2>
            <p className="text-black/50 pt-4">
              Upload your data as a CSV file or spreadsheet to get started.
            </p>
          </div>
          <p className="text-black/50 text-sm pt-8">Learn how we use your <a className="text-info/50" href="https://youtu.be/XZnuIIcc8VY?si=JtK0PQ_ervHsh10_" target="none"><u>data</u></a></p>
        </div>
        <div className="flex flex-col p-4 rounded-b-lg lg:w-5/12 shadow-lg">
          <h2 className="text-xl">
            <b className="flex gap-2">
              <FaMagnifyingGlass className="self-center" />
              Analyze
            </b>
          </h2>
          <p className="text-black/50 pt-4">
            Talk to your data, generate statistics and perform in-depth analysis.
          </p>
          <p className="text-black/50 pt-3">
            "How many users created an account this year?"
          </p>
          <p className="text-black/50 pt-1">
            "What is the average revenue generated by each user?"
          </p>
          <p className="text-black/50 pt-1">
            "How can I improve my budget to align with my goals based on this data?"
          </p>
        </div>
        <div className="flex flex-col p-4 rounded-b-lg lg:w-3/12 shadow-lg">
          <h2 className="text-xl">
            <b className="flex gap-2">
              <BsStars className="self-center" />
              Visualize
            </b>
          </h2>
          <p className="text-black/50 pt-4">
            Generate customizable Python code to visualize your data in seconds,
            or just get ready-made graphs that you can directly use.
          </p>
        </div>
      </div>

      <div className="flex flex-col md:flex-row justify-center gap-8">
        <div className="flex flex-col content-center justify-start mt-16 md:w-5/12">
          <h3 className="text-xl font-bold mb-4">Upload data to start!</h3>
          <div
            {...getRootProps()}
            className="flex flex-col bg-info/30 w-full md:w-6/7 self-center p-12 rounded-lg border-2 border-info border-dashed cursor-pointer"
          >
            <FaUpload className="self-center text-4xl m-4" />
            <input {...getInputProps()} />
            {isDragActive ? (
              <p>Drop file here ...</p>
            ) : (
              <p>Click or drag and drop</p>
            )}
          </div>
          <p className="text-black/50 text-center text-sm mt-2">
            Only .csv, .tsv, .xlsx, .xls file types are accepted (Max 1 file)
          </p>
          {acceptedFiles.length > 0 && (
            <p className="text-black/50 text-center text-sm mt-2">
              Uploaded - {acceptedFiles[0].name}
            </p>
          )}
          {fileRejections.length > 0 && (
            <p className="text-red-500 text-center text-sm mt-2">
              Error: {fileRejections[0].errors[0].message}
            </p>
          )}
        </div>
        <div className="flex flex-col content-center justify-start md:mt-16 md:w-5/12">
          <h3 className="text-xl font-bold mb-4">Or use sample data!</h3>
          <div className="flex flex-col bg-gray-600/30 w-full md:w-6/7 self-center p-12 rounded-lg border-2 border-gray-600 border-dashed cursor-pointer">
          <FaDatabase className="self-center text-4xl m-4" />
            <p>Sample data</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HomePage;
